# audacity
# Autogenerated from man page /usr/share/man/man1/audacity.1.gz
complete -c audacity -o help -d 'display a brief list of command line options'
complete -c audacity -o version -d 'display the audacity version number'
complete -c audacity -o test -d 'run self diagnostics tests (only present in development builds)'
complete -c audacity -o blocksize -d 'set the audacity block size for writing files to disk to nnn bytes'

