# btrbk
# Autogenerated from man page /usr/share/man/man1/btrbk.1.gz
complete -c btrbk -s h -l help
complete -c btrbk -l version
complete -c btrbk -s c -l config
complete -c btrbk -s n -l dry-run
complete -c btrbk -l exclude
complete -c btrbk -s p -l preserve
complete -c btrbk -l preserve-snapshots
complete -c btrbk -l preserve-backups
complete -c btrbk -l wipe
complete -c btrbk -s v -l verbose
complete -c btrbk -s q -l quiet
complete -c btrbk -s l -l loglevel
complete -c btrbk -s t -l table
complete -c btrbk -s L -l long
complete -c btrbk -l format
complete -c btrbk -l pretty
complete -c btrbk -s S -l print-schedule
complete -c btrbk -l progress
complete -c btrbk -l lockfile
complete -c btrbk -l override
complete -c btrbk -l ------------------------------------------ -d 'run                              x  x  x  x run       --preserve             …'

