# ccache
# Autogenerated from man page /usr/share/man/man1/ccache.1.gz
complete -c ccache -s c -l cleanup
complete -c ccache -s C -l clear
complete -c ccache -l config-path
complete -c ccache -s d -l directory
complete -c ccache -l evict-older-than
complete -c ccache -s h -l help
complete -c ccache -s F -l max-files
complete -c ccache -s M -l max-size
complete -c ccache -s X -l recompress
complete -c ccache -s o -l set-config
complete -c ccache -s x -l show-compression
complete -c ccache -s p -l show-config
complete -c ccache -s s -l show-stats
complete -c ccache -s V -l version
complete -c ccache -s z -l zero-stats
complete -c ccache -l checksum-file
complete -c ccache -l dump-manifest
complete -c ccache -l dump-result
complete -c ccache -l extract-result
complete -c ccache -s k -l get-config
complete -c ccache -l hash-file
complete -c ccache -l print-stats
complete -c ccache -l ccache-skip -d 'The reason this can be important is that ccache does need to parse the comman…'
complete -c ccache -o d/--directory -d 'command line option instead'
complete -c ccache -o X/--recompress -d '< 0'
complete -c ccache -s 3 -d 'corresponds to “--fast=3” for the zstd command line tool'
complete -c ccache -s 5 -d 'or so.  0 (default)'
complete -c ccache -s g -d 'with variations)'
complete -c ccache -o fdebug-prefix-map -d 'is used.  See also the discussion under Compiling in different directories'
complete -c ccache -o fmessage-length -d 'will match both'
complete -c ccache -o Wdocumentation -d 'limit_multiple (CCACHE_LIMIT_MULTIPLE)'
complete -c ccache -o fdirectives-only -d '(for GCC) or'
complete -c ccache -o frewrite-includes -d '(for Clang) to the compiler'
complete -c ccache -o index-store-path -d 'and its argument when computing the manifest hash'
complete -c ccache -o fmodules -d 'is used since it cannot hash the state of compiler\'s internal representation …'
complete -c ccache -s E -d 'oc o 2. 3'
complete -c ccache -o include
complete -c ccache -s D -d 'oc o 2. 3'
complete -c ccache -o Wp -d 'compiler option other than'
complete -c ccache -o MD
complete -c ccache -o MMD -d and
complete -c ccache -o D_define_ -d 'oc o 2. 3'
complete -c ccache -o Xpreprocessor -d 'oc o 2. 3'
complete -c ccache -s I -d 'and similar compiler options.  oc o 2. 3'
complete -c ccache -o MF -d 'oc o 2. 3'
complete -c ccache -o include-pch -d 'to include the PCH file generated from the precompiled header; or oc o 2. 3'
complete -c ccache -o fpch-preprocess -d 'when compiling'

