# cpupower-idle-set
# Autogenerated from man page /usr/share/man/man1/cpupower-idle-set.1.gz
complete -c cpupower-idle-set -s d -l disable -d 'Disable a specific processor sleep state'
complete -c cpupower-idle-set -s e -l enable -d 'Enable a specific processor sleep state'
complete -c cpupower-idle-set -s D -l disable-by-latency -d 'Disable all idle states with a equal or higher latency than <LATENCY>'

