# fltk-config
# Autogenerated from man page /usr/share/man/man1/fltk-config.1.gz
complete -c fltk-config -l api-version
complete -c fltk-config -l cc
complete -c fltk-config -l cxx
complete -c fltk-config -l cflags
complete -c fltk-config -l cxxflags
complete -c fltk-config -l compile
complete -c fltk-config -s g
complete -c fltk-config -l ldflags
complete -c fltk-config -l ldstaticflags
complete -c fltk-config -l libs
complete -c fltk-config -l use-gl
complete -c fltk-config -l use-glut
complete -c fltk-config -l use-images
complete -c fltk-config -l version

