# glmark2-es2-drm
# Autogenerated from man page /usr/share/man/man1/glmark2-es2-drm.1.gz
complete -c glmark2-es2-drm -s b -l benchmark -d 'A benchmark to run: \'scene(:opt1=val1)*\' (the option can be used multiple tim…'
complete -c glmark2-es2-drm -s f -l benchmark-file -d 'Load benchmarks to run from a file containing a list of benchmark description…'
complete -c glmark2-es2-drm -l validate -d 'Run a quick output validation test instead of running the benchmarks'
complete -c glmark2-es2-drm -l data-path -d 'Path to glmark2 models, shaders and textures'
complete -c glmark2-es2-drm -l frame-end -d 'How to end a frame [default,none,swap,finish,readpixels]'
complete -c glmark2-es2-drm -l off-screen -d 'Render to an off-screen surface'
complete -c glmark2-es2-drm -l visual-config -d 'The visual configuration to use for the rendering target: \'red=R:green=G:blue…'
complete -c glmark2-es2-drm -l reuse-context -d 'Use a single context for all scenes (by default, each scene gets its own cont…'
complete -c glmark2-es2-drm -s s -l size -d 'Size of the output window (default: 800x600)'
complete -c glmark2-es2-drm -l fullscreen -d 'Run in fullscreen mode (equivalent to --size -1x-1)'
complete -c glmark2-es2-drm -s l -l list-scenes -d 'Display information about the available scenes and their options'
complete -c glmark2-es2-drm -l show-all-options -d 'Show all scene option values used for benchmarks (only explicitly set options…'
complete -c glmark2-es2-drm -l run-forever -d 'Run indefinitely, looping from the last benchmark back to the first'
complete -c glmark2-es2-drm -l annotate -d 'Annotate the benchmarks with on-screen information (same as -b :show-fps=true…'
complete -c glmark2-es2-drm -s d -l debug -d 'Display debug messages'
complete -c glmark2-es2-drm -s h -l help -d 'Display help BENCHMARKS glmark2-es2-drm offers a suite of scenes that can be …'

