# lsbtr
# Autogenerated from man page /usr/share/man/man1/lsbtr.1.gz
complete -c lsbtr -s h -l help
complete -c lsbtr -l version
complete -c lsbtr -s l -l long
complete -c lsbtr -s u -l uuid
complete -c lsbtr -l raw
complete -c lsbtr -s v -l verbose
complete -c lsbtr -s c -l config
complete -c lsbtr -l override

