# lxc-autostart
# Autogenerated from man page /usr/share/man/man1/lxc-autostart.1.gz
complete -c lxc-autostart -l reboot -d 'Request a reboot of the container'
complete -c lxc-autostart -l shutdown -d 'Request a clean shutdown'
complete -c lxc-autostart -l kill -d 'Rather than requesting a clean shutdown of the container, explicitly kill all…'
complete -c lxc-autostart -l list -d 'Rather than performing the action, just print the container name and wait del…'
complete -c lxc-autostart -l timeout -d 'Wait TIMEOUT seconds before hard-stopping the container'
complete -c lxc-autostart -l group -d 'Comma separated list of groups to select (defaults to those without a lxc'
complete -c lxc-autostart -s a -d 'AUTOSTART AND SYSTEM BOOT The lxc-autostart command is used as part of the LX…'

