# lxc-copy
# Autogenerated from man page /usr/share/man/man1/lxc-copy.1.gz
complete -c lxc-copy -l newname -d 'The name for the copy'
complete -c lxc-copy -l newpath -d 'The path for the copy'
complete -c lxc-copy -l rename -d 'Rename the original container'
complete -c lxc-copy -l snapshot -d 'Create a snapshot of the original container'
complete -c lxc-copy -l allowrunning -d 'Allow the creation of a Snapshot of an already running container'
complete -c lxc-copy -l mount -d 'Specify a mount for a snapshot The opts argument for the mount type can by of…'
complete -c lxc-copy -l tmpfs -d 'When this option is specified the ephemeral container will be placed on a tmp…'
complete -c lxc-copy -l backingstorage -d 'Specify the backing storage type to be used for the copy where \'backingstorag…'
complete -c lxc-copy -l fssize -d 'Specify the size for an \'lvm\' filesystem'
complete -c lxc-copy -l keepname -d 'When this option is specified the hostname of the original container will be …'
complete -c lxc-copy -l keepdata -d 'When this option is specified with -e a non-ephemeral container is created an…'
complete -c lxc-copy -s e
complete -c lxc-copy -s D -d 'container is created and started'
complete -c lxc-copy -s N
complete -c lxc-copy -s m -d 'bind=/src1:/dest1:ro,bind=/src2:ro,overlay=/src3:/dest3'

