# lxc-create
# Autogenerated from man page /usr/share/man/man1/lxc-create.1.gz
complete -c lxc-create -l config -d 'Specify the configuration file to configure the virtualization and isolation …'
complete -c lxc-create -l template -d '\'template\' is the short name of an existing \'lxc-template\' script that is cal…'
complete -c lxc-create -l bdev -d '\'backingstore\' is one of \'dir\', \'lvm\', \'loop\', \'btrfs\', \'zfs\', \'rbd\', or \'bes…'
complete -c lxc-create -l dir -d 'that the container rootfs should be placed under the specified path, rather t…'
complete -c lxc-create -l lvname -d 'named \\fIlvname1 rather than the default, which is the container name'
complete -c lxc-create -l thinpool -d 'LV as a thin-provisioned volume in the pool named \\fIthinpool1 rather than th…'
complete -c lxc-create -l fstype -d 'filesystem on the LV, rather than the default, which is ext4'
complete -c lxc-create -l fssize -d 'filesystem) of size SIZE rather than the default, which is 1G'
complete -c lxc-create -l rbdname
complete -c lxc-create -l rbdpool

