# modem-manager-gui
# Autogenerated from man page /usr/share/man/man1/modem-manager-gui.1.gz
complete -c modem-manager-gui -s i -l invisible -d 'Do not show window on start'
complete -c modem-manager-gui -s m -l mmmodule -d 'Use specified modem management module'
complete -c modem-manager-gui -s c -l cmmodule -d 'Use specified connection management module'
complete -c modem-manager-gui -s l -l listmodules -d 'List all available modules and exit AUTHOR Written by Alex'

