# nload
# Autogenerated from man page /usr/share/man/man1/nload.1.gz
complete -c nload -s a -d 'Sets the length in seconds of the time window for average calculation'
complete -c nload -s i -d 'Specifies the 100% mark in kBit/s of the graph indicating the incoming bandwi…'
complete -c nload -s m -d 'Show multiple devices at a time; do not show the traffic graphs'
complete -c nload -s o -d 'Same as -i but for the graph indicating the outgoing bandwidth usage'
complete -c nload -s t -d 'Determines the refresh interval of the display in milliseconds'
complete -c nload -s u -d 'Sets the type of unit used for the display of traffic numbers'
complete -c nload -s U -d 'Same as -u, but for an amount of data, e. g.  Bit, kByte, GBit etc'
complete -c nload -s h -l help -d 'Show a short summary of these command line options'

