# ofonod
# Autogenerated from man page /usr/share/man/man8/ofonod.8.gz
complete -c ofonod -l debug -s d -d 'Enable debug information output'
complete -c ofonod -l nodetach -s n -d 'Don\'t run as daemon in background'

