# peg
# Autogenerated from man page /usr/share/man/man1/peg.1.gz
complete -c peg -s h -d 'prints a summary of available options and then exits'
complete -c peg -o ooutput -d 'writes the generated parser to the file  output instead of the standard output'
complete -c peg -s P -d 'suppresses #line directives in the output'
complete -c peg -s v -d 'writes verbose information to standard error while working'
complete -c peg -s V -d 'writes version information to standard error then exits'

