# pipewire
# Autogenerated from man page /usr/share/man/man1/pipewire.1.gz
complete -c pipewire -s h -l help -d 'Show help'
complete -c pipewire -l version -d 'Show version information'
complete -c pipewire -s n -l name -d 'Set the daemon name (Default pipewire-0)'

