# schedtool
# Autogenerated from man page /usr/share/man/man8/schedtool.8.gz
complete -c schedtool -s N -s 0 -d 'set all PIDs to SCHED_NORMAL/OTHER'
complete -c schedtool -s F -s 1 -d 'to SCHED_FIFO   root-credentials required'
complete -c schedtool -s R -s 2 -d 'to SCHED_RR     root-credentials required'
complete -c schedtool -s B -s 3 -d 'to SCHED_BATCH'
complete -c schedtool -s I -s 4 -d 'to SCHED_ISO'
complete -c schedtool -s D -s 5 -d 'to SCHED_IDLEPRIO'
complete -c schedtool -s M -d 'for manual/raw mode; policy is the number of the scheduling policy (see above…'
complete -c schedtool -s p -d 'specify static priority required for SCHED_FIFO and SCHED_RR'
complete -c schedtool -s a -d 'set the PID\'s affinity to this bitmask (hexadecimal); alternatively, a list m…'
complete -c schedtool -s n -d 'set the PID\'s nice level; see nice(2), nice(1)'
complete -c schedtool -s e -d 'execute command with given scheduling parameters (overwrites schedtool\'s proc…'
complete -c schedtool -s r -d 'display min and max priority for each policy'
complete -c schedtool -s v -d 'be verbose'

