# ssh_filter_btrbk
# Autogenerated from man page /usr/share/man/man1/ssh_filter_btrbk.1.gz
complete -c ssh_filter_btrbk -s s -l source
complete -c ssh_filter_btrbk -s t -l target
complete -c ssh_filter_btrbk -s d -l delete
complete -c ssh_filter_btrbk -s i -l info
complete -c ssh_filter_btrbk -l snapshot
complete -c ssh_filter_btrbk -l send
complete -c ssh_filter_btrbk -l receive
complete -c ssh_filter_btrbk -s p -l restrict-path
complete -c ssh_filter_btrbk -s l -l log
complete -c ssh_filter_btrbk -l sudo

