# surl
# Autogenerated from man page /usr/share/man/man1/surl.1.gz
complete -c surl -s h -l help -d ' This help message'
complete -c surl -s v -l version -d ' Prints version info'
complete -c surl -s c -l url -d ' URL to shorten'
complete -c surl -s a -l api-key -d ' Use an API key'
complete -c surl -s f -l file -d ' Read input from filename'
complete -c surl -s i -l in-place -d ' Save changes to file directly (Requires: -f)'
complete -c surl -s l -l links-only -d ' Output only a list of links (old_url => shortened_url)'
complete -c surl -s o -l output -d ' Output to file'
complete -c surl -s p -l password -d ' Your password'
complete -c surl -s q -l quiet -d ' Suppress any extra messages'
complete -c surl -s t -l title -d ' Title (short custom name/alias) for the url'
complete -c surl -s u -l username -d ' Your username'
complete -c surl -s s -l service -d ' The URL shortening service to use (Default: tinyurl. com)'
complete -c surl -s r -l script -d ' The surlscript to execute'

