# virt-qemu-run
# Autogenerated from man page /usr/share/man/man1/virt-qemu-run.1.gz
complete -c virt-qemu-run -s h -l help
complete -c virt-qemu-run -s v -l verbose
complete -c virt-qemu-run -s r -l root
complete -c virt-qemu-run -s s -l secret

