# yadm
# Autogenerated from man page /usr/share/man/man1/yadm.1.gz
complete -c yadm -s Y -l yadm-dir -d 'Override the yadm directory'
complete -c yadm -l yadm-data -d 'Override the yadm data directory'
complete -c yadm -l yadm-repo -d 'Override the location of the yadm repository'
complete -c yadm -l yadm-config -d 'Override the location of the yadm configuration file'
complete -c yadm -l yadm-encrypt -d 'Override the location of the yadm encryption configuration'
complete -c yadm -l yadm-archive -d 'Override the location of the yadm encrypted files archive'
complete -c yadm -s w -d 'yadm can be forced to overwrite an existing repository by providing the'
complete -c yadm -s f -d 'If you want to use a branch other than the remote HEAD branch you can specify…'
complete -c yadm -s b -d 'By default yadm will ask the user if the bootstrap program should be run (if …'
complete -c yadm -l bootstrap -l no-bootstrap -d 'will either force the bootstrap to be run, or prevent it from being run, with…'
complete -c yadm -s l -d 'option will list the files stored without extracting them'
complete -c yadm -l yadm-bootstrap -d 'Override the location of the yadm bootstrap program'

