#!/bin/bash
if [[ "$(mount | grep '/dev/sda2 on / type btrfs')" == *"subvol=/ROOT)"* ]];then 
    if [ -n "$(yadm diff --name-only)" ]; then
        echo -e "ARQUIVOS MODIFICADOS:\n$(yadm diff --name-only)\n"
        yadm diff
    fi
    yadm commit -a -m "atualizando"
else
    echo -e "Você não está no subvolume ROOT. push não realizado"
fi
