#!/bin/bash
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root";
    exit
fi
touch /tmp/btrbk.sh.pid
if [[ ! "$(mount | grep '/dev/sda2 on / type btrfs')" == *"subvol=/ROOT)"* ]]; then
    notify-send 'Você não está no subvolume ROOT. Snapshot não foi criado.';
    echo 'Você não está no subvolume ROOT. Snapshot não foi criado.'
    rm /tmp/btrbk.sh.pid;
    exit 1
fi
while [ -n "$(pgrep UNO)" ] || [ -n "$(pgrep Diablo)" ] ||  [ -n "$(pgrep qemu)" ];
do
   sleep 10;
done
btrbk -c /etc/btrbk/btrbk_home.conf -q run;
btrbk -c /etc/btrbk/btrbk_root.conf -q run;  
rm /tmp/btrbk.sh.pid;
