#!/bin/bash
if [ "$EUID" -ne 0 ]; then
    /usr/bin/echo "Please run as root";
    exit
fi
/usr/bin/touch /tmp/btrbk.sh.pid
if [[ ! "$(/usr/bin/mount | /usr/bin/grep '/dev/sda2 on / type btrfs')" == *"subvol=/ROOT)"* ]]; then
    /usr/bin/notify-send 'Você não está no subvolume ROOT. Snapshot não foi criado.';
    /usr/bin/echo 'Você não está no subvolume ROOT. Snapshot não foi criado.'
    /usr/bin/rm /tmp/btrbk.sh.pid;
    exit 1
fi
while [ -n "$(/usr/bin/pgrep wine)" ] ||  [ -n "$(/usr/bin/pgrep steam)" ];
do
   /usr/bin/sleep 10;
done
/usr/bin/btrbk -c /etc/btrbk/btrbk_home.conf -q run;
#fazer chegagem de erro
/usr/bin/btrbk -c /etc/btrbk/btrbk_root.conf -q run;  
#fazer chegagem de erro
/usr/bin/rm /tmp/btrbk.sh.pid;

