#!/bin/bash
export LC_ALL=C #performance-wise line
case $1 in
    'play_pause')
        if [ -n "$(/usr/bin/pgrep -x spotify)" ];
        then
            /usr/bin/playerctl --no-messages --player=spotify play-pause &
            exit
        elif [ -n "$(/usr/bin/pgrep -x mpv)" ];then
            /usr/bin/playerctl --no-messages --player=mpv play-pause &
            exit
        else
            /usr/bin/playerctl --no-messages play-pause &
            exit
        fi
    ;;
    'previous')
        if [ -n "$(/usr/bin/pgrep -x spotify)" ];
        then
            /usr/bin/playerctl --no-messages --player=spotify previous &
            exit
        elif [ -n "$(/usr/bin/pgrep -x mpv)" ];then
            /usr/bin/playerctl --no-messages --player=mpv previous &
            exit
        else
            /usr/bin/playerctl --no-messages previous &
            exit
        fi
    ;;
    'next')
        if [ -n "$(/usr/bin/pgrep -x spotify)" ];
        then
            /usr/bin/playerctl --no-messages --player=spotify next &
            exit
        elif [ -n "$(/usr/bin/pgrep -x mpv)" ];then
            /usr/bin/playerctl --no-messages --player=mpv next &
            exit
        else
            /usr/bin/playerctl --no-messages next &
            exit
        fi
    ;;
    'avancar_posicao')
        /usr/bin/playerctl --no-messages position 10+ &
    ;;
    'voltar_posicao')
        /usr/bin/playerctl --no-messages position 10- &
    ;;
esac
#old code
# if [ "$1" == 'play_pause' ]; then
#     if [ -n "$(/usr/bin/pgrep -x spotify)" ];
#     then
#         /usr/bin/playerctl --no-messages --player=spotify play-pause &
#         exit
#     elif [ -n "$(/usr/bin/pgrep -x mpv)" ];then
#         /usr/bin/playerctl --no-messages --player=mpv play-pause &
#         exit
#     else
#         /usr/bin/playerctl --no-messages play-pause &
#         exit
#     fi
# elif [ "$1" == 'previous' ]; then
#     if [ -n "$(/usr/bin/pgrep -x spotify)" ];
#     then
#         /usr/bin/playerctl --no-messages --player=spotify previous &
#         exit
#     elif [ -n "$(/usr/bin/pgrep -x ncspot)" ];then
#         /usr/bin/playerctl --no-messages --player=ncspot previous &
#         exit
#     else
#         /usr/bin/playerctl --no-messages previous &
#         exit
#     fi
# elif [ "$1" == 'next' ]; then
#     if [ -n "$(/usr/bin/pgrep -x spotify)" ];
#     then
#         /usr/bin/playerctl --no-messages --player=spotify next &
#         exit
#     elif [ -n "$(/usr/bin/pgrep -x ncspot)" ];then
#         /usr/bin/playerctl --no-messages --player=ncspot next &
#         exit
#     else
#         /usr/bin/playerctl --no-messages next &
#         exit
#     fi
# elif [ "$1" == 'avancar_posicao' ]; then
#      /usr/bin/playerctl position 10+ &
#      exit
# elif [ "$1" == 'voltar_posicao' ]; then
#      /usr/bin/playerctl position 10- &
#      exit
# fi
