#!/bin/bash
if [ "$1" == 'play_pause' ]; then
    if [ -n "$(/usr/bin/pgrep -x spotify)" ];
    then
        /usr/bin/playerctl --player=spotify play-pause;
    elif [ -n "$(/usr/bin/pgrep -x ncspot)" ];then
        if [ "$(/usr/bin/playerctl --player=ncspot status)" == "Playing" ]; then
            /usr/bin/playerctl --player=ncspot pause;
        elif [ "$(/usr/bin/playerctl --player=ncspot status)" == "Paused" ]; then
            /usr/bin/playerctl --player=ncspot play;
        fi
    else
        /usr/bin/playerctl play-pause;
    fi
elif [ "$1" == 'previous' ]; then
    if [ -n "$(/usr/bin/pgrep -x spotify)" ];
    then
        /usr/bin/playerctl --player=spotify previous;
    elif [ -n "$(/usr/bin/pgrep -x ncspot)" ];then
        /usr/bin/playerctl --player=ncspot previous;  
    else
        /usr/bin/playerctl previous;
    fi
elif [ "$1" == 'next' ]; then
    if [ -n "$(/usr/bin/pgrep -x spotify)" ];
    then
        /usr/bin/playerctl --player=spotify next;
    elif [ -n "$(/usr/bin/pgrep -x ncspot)" ];then
        /usr/bin/playerctl --player=ncspot next;  
    else
        /usr/bin/playerctl next;
    fi
fi
